version: '3'
services:
  www:
    image: my-php:latest
    volumes:
      - "./src/:/var/www/html"
    ports:
      - 80:80
  
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=php
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306